apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-canary
  namespace: nodejs-canary
  labels:
    app: nodejs-app
    stage: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      stage: canary
  template:
    metadata:
      labels:
        app: nodejs-app
        stage: canary
    spec:
      containers:
      - name: nodejs-app
        image: nginx:1.23
        env:
        - name: PRODUCTION_STATE
          value: "live"
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"