apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nodejs-app
        env:
        - name: PRODUCTION_STATE
          value: "live"