{{- if .Values.deployment.setProductionState }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  PRODUCTION_STATE: "test"
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.services.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-config
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
  strategy:
    blueGreen:
      activeService: {{ .Values.services.active }}
      previewService: {{ .Values.services.preview }}
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
        - templateName: promote-canary-analysis
        args:
        - name: config-name
          value: {{ .Values.app.name }}-config
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: promote-canary-analysis
  namespace: {{ .Release.Namespace }}
spec:
  args:
  - name: config-name
  metrics:
  - name: update-config-to-live
    count: 1
    interval: 10s
    successCondition: "true"
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: update-config
                image: bitnami/kubectl:latest
                command: ["/bin/sh"]
                args: ["-c", "sleep 5 && kubectl patch configmap {{.args.config-name}} -p '{\"data\":{\"PRODUCTION_STATE\":\"live\"}}' -n {{ .Release.Namespace }} && echo 'Step 2: promote_canary - Updated PRODUCTION_STATE=live' && sleep 5"]
              restartPolicy: Never
              serviceAccountName: argo-rollouts

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.active }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.services.port }}
      targetPort: {{ .Values.services.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.preview }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.services.port }}
      targetPort: {{ .Values.services.port }}
  type: ClusterIP
{{- end }}
