apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-install
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.37.7
    helm:
      values: |
        installCRDs: true
        controller:
          replicas: 1
  destination:
    server: arn:aws:eks:us-west-1:501294308535:cluster/prod-eks
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true