apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app-ecr
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://501294308535.dkr.ecr.us-west-1.amazonaws.com
    chart: nodejs-app
    targetRevision: 0.1.0
    helm:
      values: |
        replicaCount: 2
        image:
          repository: nginx
          tag: "latest"
        service:
          type: ClusterIP
          port: 80

  destination:
    server: arn:aws:eks:us-west-1:501294308535:cluster/staging-eks
    namespace: sample-app-ecr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
