apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-canary-git
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/moitrasayan007/k8s-eks-argocd-capabilities
    targetRevision: master
    path: .
    directory:
      include: "canary-active.yaml"
  destination:
    server: arn:aws:eks:us-west-1:501294308535:cluster/staging-eks
    namespace: nodejs-canary
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true