apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/moitrasayan007/k8s-eks-argocd-capabilities.git
    targetRevision: master
    path: app-v3
  destination:
    name: prod-eks-1
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
